const $ = id => document.getElementById(id);
const esc = v => String(v ?? "").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]));
const fmt = v => Number(v||0).toLocaleString("fr-FR");

async function api(url, options={}) {
  const r = await fetch(url, {credentials:"same-origin", ...options});
  const d = await r.json().catch(()=>({}));
  if(!r.ok) throw new Error(d.error || `Erreur serveur (${r.status})`);
  return d;
}
function online(v){ $("status").className=`status ${v?"online":"offline"}`; $("status").textContent=v?"● Xyro en ligne":"● Hors ligne"; }

async function stats(){ const d=await api('/api/admin/stats'); $("sUsers").textContent=fmt(d.users);$("sMessages").textContent=fmt(d.messages);$("sMemories").textContent=fmt(d.memories);$("sProjects").textContent=fmt(d.projects);$("sAlerts").textContent=fmt(d.open_alerts);$("sReports").textContent=fmt(d.open_reports);online(d.status==='online'); }

function renderUsers(list){ const box=$("users"); if(!list?.length){box.innerHTML='<div class="empty">🔎<br>Aucun compte trouvé.</div>';return;} box.innerHTML=list.map(u=>`<button class="user" onclick="loadUser('${encodeURIComponent(u.public_id)}')"><div class="avatar">${esc((u.username||'?')[0].toUpperCase())}</div><div class="usertext"><b>${esc(u.username)}</b><span>${esc(u.public_id)}</span><small>Créé le ${esc(u.created_at||'inconnu')}</small>${u.is_admin?'<em>🛡️ Administrateur</em>':(u.banned?'<em>🔨 Banni</em>':'')}</div><strong>›</strong></button>`).join(''); }
async function users(q=''){ try{const d=await api(q?'/api/admin/search-users?q='+encodeURIComponent(q):'/api/admin/users');renderUsers(d.users||[]);}catch(e){$("users").innerHTML=`<div class="error">⚠️ ${esc(e.message)}</div>`;} }

async function alerts(){try{const d=await api('/api/admin/alerts');const b=$("alerts");if(!d.alerts?.length){b.innerHTML='<div class="empty">✅<br>Aucune alerte.</div>';return;}b.innerHTML=d.alerts.map(a=>`<article class="alert ${a.reviewed?'reviewed':''}"><div><b>${esc(a.category)}</b><span>${esc(a.severity)}</span></div><p>${esc(a.message_excerpt)}</p><small>${esc(a.created_at)} · ${esc(a.user_id)}</small>${a.reviewed?'':'<button onclick="reviewAlert('+Number(a.id)+')">Marquer comme vue</button>'}</article>`).join('');}catch(e){$("alerts").innerHTML=`<div class="error">⚠️ ${esc(e.message)}</div>`;}}
async function reviewAlert(id){await api(`/api/admin/alerts/${id}/review`,{method:'POST'});await Promise.all([alerts(),stats()]);}
async function reports(){try{const d=await api('/api/admin/reports');const b=$("reports");if(!d.reports?.length){b.innerHTML='<div class="empty">✅<br>Aucun signalement.</div>';return;}b.innerHTML=d.reports.map(r=>`<article class="alert ${r.status!=="pending"?'reviewed':''}"><div><b>${esc(r.reported_username||r.reported_id)}</b><span>${esc(r.status)}</span></div><p><strong>Motif :</strong> ${esc(r.reason)}<br>${esc(r.details||'Aucun détail fourni.')}</p><small>Par ${esc(r.reporter_username||r.reporter_id)} · ${esc(r.created_at)}</small>${r.status==='pending'?`<div style="display:flex;gap:8px;margin-top:10px"><button onclick="reviewReport(${Number(r.id)},'reviewed')">Traiter</button><button onclick="reviewReport(${Number(r.id)},'rejected')">Rejeter</button></div>`:''}</article>`).join('');}catch(e){$("reports").innerHTML=`<div class="error">⚠️ ${esc(e.message)}</div>`;}}
async function reviewReport(id,status){await api(`/api/admin/reports/${id}/review`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({status})});await Promise.all([reports(),stats()]);}

function banControls(u){ if(u.is_admin) return '<div class="admin-note">🛡️ Compte administrateur protégé.</div>'; if(u.banned) return `<div class="ban-box danger"><b>🔨 Compte actuellement banni</b><p>${esc(u.ban_reason||'Aucune raison')}</p><small>Expire : ${u.ban_expires_at?esc(u.ban_expires_at):'Jamais'}</small><button class="danger-btn" onclick="unbanUser('${encodeURIComponent(u.public_id)}')">Débannir</button></div>`; return `<div class="ban-box"><b>🔨 Bannir cet utilisateur</b><div class="ban-row"><select id="banDuration"><option value="10m">10 minutes</option><option value="1h">1 heure</option><option value="6h">6 heures</option><option value="1d">24 heures</option><option value="7d">7 jours</option><option value="30d">30 jours</option><option value="permanent">Permanent</option></select><input id="banReason" maxlength="500" placeholder="Raison du ban"><button class="danger-btn" onclick="banUser('${encodeURIComponent(u.public_id)}')">Bannir</button></div></div>`;}

async function loadUser(id){id=decodeURIComponent(id);try{const d=await api('/api/admin/user/'+encodeURIComponent(id));const u=d.user;$("selected").textContent=`${u.username} · ${u.public_id}`;let sessions={};(d.messages||[]).forEach(m=>(sessions[m.session_id||'Sans session']??=[]).push(m));$("details").innerHTML=`<div class="profile"><div class="big-avatar">${esc((u.username||'?')[0].toUpperCase())}</div><div><h3>${esc(u.username)}</h3><p>${esc(u.public_id)}</p><small>Créé le ${esc(u.created_at)}</small></div></div>${banControls(u)}<h3 class="sub">💬 Conversations (${fmt(u.message_count)})</h3><div class="convos">${Object.entries(sessions).map(([sid,msgs])=>`<div class="conversation"><b>Session ${esc(sid)}</b>${msgs.map(m=>`<div class="msg ${m.role==='user'?'from-user':'from-ai'}"><strong>${m.role==='user'?'Utilisateur':'Xyro.AI'}</strong><p>${esc(m.content)}</p><small>${esc(m.created_at)}</small></div>`).join('')}</div>`).join('')||'<div class="empty">Aucun message.</div>'}</div><h3 class="sub">🧠 Mémoire (${fmt(u.memory_count)})</h3><div class="list">${(d.memories||[]).map(m=>`<div><p>${esc(m.content)}</p><small>${esc(m.created_at)}</small></div>`).join('')||'<div class="empty">Aucune mémoire.</div>'}</div><h3 class="sub">📁 Projets (${fmt(u.project_count)})</h3><div class="list">${(d.projects||[]).map(p=>`<div><b>${esc(p.name)}</b><p>${esc(p.context||'')}</p><small>${esc(p.updated_at)}</small></div>`).join('')||'<div class="empty">Aucun projet.</div>'}</div>`;}catch(e){$("details").innerHTML=`<div class="error">⚠️ ${esc(e.message)}</div>`;}}

async function banUser(id){const duration=$("banDuration")?.value;const reason=$("banReason")?.value||'';try{await api('/api/admin/user/'+id+'/ban',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({duration,reason})});await loadUser(id);await Promise.all([users($("search").value.trim()),stats()]);}catch(e){alert(e.message);}}
async function unbanUser(id){try{await api('/api/admin/user/'+id+'/unban',{method:'POST'});await loadUser(id);await Promise.all([users($("search").value.trim()),stats()]);}catch(e){alert(e.message);}}

async function refresh(){await Promise.all([stats(),users($("search").value.trim()),alerts(),reports()]);}
async function enter(){try{const d=await api('/api/admin/me');if(d.authenticated){$("login").classList.add('hidden');$("app").classList.remove('hidden');$("adminName").textContent='Connecté : '+(d.user?.username||'admin');await refresh();return;}}catch{} online(false);}
$("loginBtn").onclick=async()=>{try{const d=await api('/api/admin/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:$("username").value.trim(),password:$("password").value})});$("loginError").textContent='';$("login").classList.add('hidden');$("app").classList.remove('hidden');$("adminName").textContent='Connecté : '+(d.user?.username||'admin');await refresh();}catch(e){$("loginError").textContent='⚠️ '+e.message;}};
$("password").onkeydown=e=>{if(e.key==='Enter')$("loginBtn").click()};$("searchBtn").onclick=()=>users($("search").value.trim());$("search").onkeydown=e=>{if(e.key==='Enter')$("searchBtn").click()};$("refresh").onclick=refresh;$("logout").onclick=async()=>{await api('/api/admin/logout',{method:'POST'}).catch(()=>{});location.reload();};
window.loadUser=loadUser;window.banUser=banUser;window.unbanUser=unbanUser;window.reviewAlert=reviewAlert;window.reviewReport=reviewReport;enter();
